services:
  - type: web
    name: ocean-backend
    env: python
    plan: free

    buildCommand: "./build.sh"
    startCommand: "gunicorn ocean_backend.wsgi:application"

    envVars:
      DJANGO_SETTINGS_MODULE: "ocean_backend.settings"
      PYTHON_VERSION: "3.10"

    disk:
      name: media
      mountPath: /opt/render/project/src/ocean_backend/media
      sizeGB: 1
