services:
  - type: web
    name: ocean-backend
    env: python
    plan: free

    buildCommand: "pip install -r ocean_backend/requirements.txt && python manage.py migrate sites --fake"
    startCommand: "cd ocean_backend && gunicorn ocean_backend.wsgi:application --workers 1 --timeout 120"

    envVars:
      DJANGO_SETTINGS_MODULE: "ocean_backend.ocean_backend.settings"
      PYTHON_VERSION: "3.10"
      # DATABASE_URL will be injected from Render PostgreSQL automatically
